@startuml Oven
[*] --> Heating
Heating: entry/heaterOn();
Heating: exit/heaterOff();
Heating --> DoorOpen: DoorOpen
DoorOpen --> Heating: DoorClose
state Heating {
    Heating --> Toasting: DoToasting
    Heating --> Baking: DoBaking

}

@enduml